apiVersion: apps/v1
kind: Deployment
metadata:
  name: architecture-exercise-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: architecture-exercise-api
  template:
    metadata:
      labels:
        app: architecture-exercise-api
    spec:
      containers:
        - name: architecture-exercise-api
          image: TU_USUARIO_DOCKERHUB/architecture-exercise:1.0
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
            - name: ASPNETCORE_URLS
              value: "http://+:8080"
            - name: ConnectionStrings__DefaultConnection
              value: "Host=postgresql-service;Port=5432;Database=Invoices;Username=admin;Password=1234"